[pytest]
testpaths = tests
python_files = test_*_pytest.py
python_classes = Test*
python_functions = test_*
addopts = -v -s --html=reports/html_reports/pytest_report.html --self-contained-html
markers =
    smoke: Quick smoke tests
    regression: Full regression suite tests
    login: Authentication and login related tests
    search: Product search functionality tests
    datadriven: Data-driven tests using external CSV files
